# -*- coding: utf-8 -*-
"""NPS1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOOU58uqHrC0Wo2xQKWjdANY7JbN9aY0
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --- CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(page_title="NPS Dashboard 2025", layout="wide")

# --- ESTILO DARK MODE Y TARJETAS ---
st.markdown("""
    <style>
    /* Fondo negro para la aplicación */
    .stApp {
        background-color: #0E1117;
        color: #FFFFFF;
    }
    /* Estilo de las tarjetas editables */
    .card {
        background-color: #1E1E1E;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.5);
        margin-bottom: 20px;
        border: 1px solid #333;
    }
    .emoji-grande { font-size: 80px; text-align: center; color: #FFD700; }
    .header-naranja {
        background-color: #FF8C00;
        color: white;
        padding: 8px;
        border-radius: 5px;
        text-align: center;
        font-weight: bold;
        margin-bottom: 15px;
    }
    /* Ajuste de inputs para modo oscuro */
    input, textarea {
        background-color: #262730 !important;
        color: white !important;
        border: 1px solid #444 !important;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 1. CARGA DE DATOS ---
@st.cache_data
def load_data():
    df = pd.read_excel('Base bruta dic.xlsx')
    df['Primary Driver'] = df['Primary Driver'].astype(str).replace('nan', 'N/A')
    df['Secondary Driver'] = df['Secondary Driver'].astype(str).replace('nan', 'N/A')
    df['Category'] = df['Category'].astype(str).replace('nan', 'N/A')
    df['Score'] = pd.to_numeric(df['Score'], errors='coerce').fillna(0)
    df['Survey Completed Date'] = pd.to_datetime(df['Survey Completed Date'])
    return df

df = load_data()

# Obtener mes dinámico para el título
mes_actual = df['Survey Completed Date'].dt.month_name().iloc[0]

# --- TÍTULO PRINCIPAL ---
st.markdown(f"<h1 style='text-align: center; color: #FFD700;'>NPS 2025 - {mes_actual}</h1>", unsafe_allow_html=True)

# --- 2. RESUMEN GLOBAL (ESTÁTICO) ---
st.subheader("📊 Resumen General")
col_est_1, col_est_2 = st.columns(2)

with col_est_1:
    data_anillo = df.groupby('Primary Driver')['Customer ID'].count().reset_index()
    fig_anillo = px.pie(data_anillo, values='Customer ID', names='Primary Driver', 
                        hole=0.6, title="Primary Driver Composition",
                        color_discrete_sequence=['#FFFF00', '#FFD700', '#FFEA00', '#FDDA0D'])
    fig_anillo.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_anillo, use_container_width=True)

with col_est_2:
    data_lineas = df.groupby('Primary Driver')['Score'].mean().sort_values(ascending=False).reset_index()
    fig_lineas = px.line(data_lineas, x='Primary Driver', y='Score', markers=True,
                         title="Average Score per Primary Driver")
    fig_lineas.update_traces(line_color='#FFD700', marker=dict(size=10, color='#FFD700'))
    fig_lineas.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', yaxis_range=[6, 10])
    st.plotly_chart(fig_lineas, use_container_width=True)

st.divider()

# --- 3. PANEL INTERACTIVO (DINÁMICO) ---
st.sidebar.header("Filtros de Segmentación")
driver_list = ['All'] + sorted(df['Primary Driver'].unique().tolist())
driver_select = st.sidebar.selectbox("Primary Driver:", driver_list)

cat_options = sorted([c for c in df['Category'].unique().tolist() if c != 'N/A'])
cat_select = st.sidebar.multiselect("Categorías:", cat_options, default=cat_options)

# Filtrado
df_filt = df if driver_select == 'All' else df[df['Primary Driver'] == driver_select]
df_sec = df_filt[df_filt['Category'].isin(cat_select)]

st.subheader(f"🔍 Detalle Segmentado: {driver_select}")
col_din_1, col_din_2, col_din_3 = st.columns(3)

with col_din_1:
    df_vis = df_filt[df_filt['Category'] != 'N/A']
    conteo_cat = df_vis['Category'].value_counts(normalize=True).reset_index()
    conteo_cat.columns = ['Category', 'Percentage']
    fig_nps = px.bar(conteo_cat, x='Category', y='Percentage', color='Category',
                     color_discrete_map={'Detractor': '#E74C3C', 'Passive': '#BDC3C7', 'Promoter': '#F1C40F'},
                     title="Category Composition %")
    fig_nps.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_nps, use_container_width=True)

with col_din_2:
    if not df_sec.empty:
        vol_data = df_sec['Secondary Driver'].value_counts().reset_index().sort_values(by='count')
        fig_vol = px.bar(vol_data, y='Secondary Driver', x='count', orientation='h', 
                         title="Volume by Secondary Driver", color_discrete_sequence=['#FFEA00'])
        fig_vol.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)')
        st.plotly_chart(fig_vol, use_container_width=True)

with col_din_3:
    if not df_sec.empty:
        score_data = df_sec.groupby('Secondary Driver')['Score'].mean().reset_index().sort_values(by='Score', ascending=False)
        fig_score = px.bar(score_data, x='Secondary Driver', y='Score', title="Avg Score by Sec. Driver",
                           color_discrete_sequence=['#FDDA0D'])
        ymin = max(0, score_data['Score'].min() - 0.5)
        fig_score.update_layout(template="plotly_dark", paper_bgcolor='rgba(0,0,0,0)', yaxis_range=[ymin, 10])
        st.plotly_chart(fig_score, use_container_width=True)

# --- 4. SECCIÓN COMMENTS CHOSEN ---
st.divider()
st.markdown("<h2 style='text-align: center;'>☹ COMMENTS CHOSEN</h2>", unsafe_allow_html=True)
t1, t2, t3 = st.columns(3)

for i, col in enumerate([t1, t2, t3]):
    with col:
        st.markdown(f"""
        <div class="card">
            <div class="emoji-grande">☹</div>
        </div>
        """, unsafe_allow_html=True)
        # Título editable naranja
        driver_title = st.text_input(f"Título {i+1}", f"Secondary Driver {i+1}", key=f"t{i}")
        st.markdown(f"<div class='header-naranja'>{driver_title}</div>", unsafe_allow_html=True)
        
        # Inputs de datos
        st.text_input("Cliente:", key=f"cli{i}")
        st.number_input("Score:", 0, 10, key=f"sc{i}")
        st.text_area("Comentario:", key=f"com{i}", height=100)
        st.text_input("Camión:", key=f"cam{i}")
