# -*- coding: utf-8 -*-
"""NPS1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOOU58uqHrC0Wo2xQKWjdANY7JbN9aY0
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import textwrap

# Configuración de página
st.set_page_config(page_title="Dashboard NPS Dic", layout="wide")

# Estilos CSS para las tarjetas
st.markdown("""
    <style>
    .card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.05);
        margin-bottom: 20px;
    }
    .emoji { font-size: 70px; text-align: center; color: #FFD700; }
    .header-naranja {
        background-color: #FF8C00;
        color: white;
        padding: 5px;
        border-radius: 5px;
        text-align: center;
        font-weight: bold;
    }
    </style>
    """, unsafe_allow_html=True)

# 1. CARGA DE DATOS
@st.cache_data
def load_data():
    df = pd.read_excel('Base bruta dic.xlsx')
    df['Primary Driver'] = df['Primary Driver'].astype(str).replace('nan', 'N/A')
    df['Secondary Driver'] = df['Secondary Driver'].astype(str).replace('nan', 'N/A')
    df['Category'] = df['Category'].astype(str).replace('nan', 'N/A')
    df['Score'] = pd.to_numeric(df['Score'], errors='coerce').fillna(0)
    return df

df = load_data()

# 2. FILTROS (SIDEBAR)
st.sidebar.header("Filtros")
driver_select = st.sidebar.selectbox("Primary Driver:", ['All'] + sorted(df['Primary Driver'].unique().tolist()))
cat_options = sorted([c for c in df['Category'].unique().tolist() if c != 'N/A'])
cat_select = st.sidebar.multiselect("Categorías:", cat_options, default=cat_options)

# Filtrado
df_filt = df if driver_select == 'All' else df[df['Primary Driver'] == driver_select]
df_sec = df_filt[df_filt['Category'].isin(cat_select)]

# 3. GRÁFICAS (Utilizando Plotly para que sean interactivas en la web)
st.title("📊 Dashboard Operativo NPS")

col1, col2, col3 = st.columns(3)

with col1:
    df_vis = df_filt[df_filt['Category'] != 'N/A']
    nps_data = df_vis['Category'].value_counts(normalize=True).reset_index()
    fig1 = px.bar(nps_data, x='Category', y='proportion', color='Category',
                 color_discrete_map={'Detractor': '#E74C3C', 'Passive': '#BDC3C7', 'Promoter': '#F1C40F'},
                 title="NPS Composition %")
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    if not df_sec.empty:
        vol_data = df_sec['Secondary Driver'].value_counts().reset_index().sort_values(by='count')
        fig2 = px.bar(vol_data, y='Secondary Driver', x='count', orientation='h', title="Vol. Secondary Driver")
        fig2.update_traces(marker_color='#FFD700')
        st.plotly_chart(fig2, use_container_width=True)

with col3:
    if not df_sec.empty:
        score_data = df_sec.groupby('Secondary Driver')['Score'].mean().reset_index().sort_values(by='Score', ascending=False)
        fig3 = px.bar(score_data, x='Secondary Driver', y='Score', title="Avg Score Sec. Driver")
        fig3.update_traces(marker_color='#F4D03F')
        fig3.update_yaxes(range=[score_data['Score'].min()-0.5, 10])
        st.plotly_chart(fig3, use_container_width=True)

# 4. COMMENTS CHOSEN
st.divider()
st.subheader("☹ COMMENTS CHOSEN")
t1, t2, t3 = st.columns(3)

for i, col in enumerate([t1, t2, t3]):
    with col:
        st.markdown("<div class='emoji'>☹</div>", unsafe_allow_html=True)
        # En Streamlit los inputs son diferentes, aquí los creamos:
        st.text_input("Driver Title", f"Secondary Driver {i+1}", key=f"h{i}")
        st.text_input("Cliente", key=f"c{i}")
        st.number_input("Score", 0, 10, key=f"s{i}")
        st.text_area("Comentario", key=f"co{i}")
        st.text_input("Camión", key=f"ca{i}")